# Generated by Django 3.0.2 on 2020-07-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourseModel',
            fields=[
                ('cno', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('cdate', models.DateField()),
                ('ctime', models.TimeField()),
                ('fee', models.FloatField()),
                ('dur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('upass', models.CharField(max_length=10)),
            ],
        ),
    ]
