# Generated by Django 3.0.2 on 2020-07-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcoursemodel',
            name='dur',
            field=models.CharField(max_length=20),
        ),
    ]
