# Generated by Django 3.0.2 on 2020-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200714_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcoursemodel',
            name='dur',
            field=models.IntegerField(),
        ),
    ]
