# Generated by Django 3.0.2 on 2020-07-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200715_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
