# Generated by Django 3.0.2 on 2020-07-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_adminmodel_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminModel',
            new_name='LoginModel',
        ),
    ]
