# Generated by Django 3.0.2 on 2020-07-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200717_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=30)),
                ('semail', models.EmailField(max_length=50)),
                ('smobno', models.IntegerField()),
                ('sgender', models.CharField(max_length=7)),
                ('sdob', models.DateField()),
                ('saddrs', models.CharField(max_length=100)),
                ('scity', models.CharField(max_length=40)),
                ('spincode', models.IntegerField()),
                ('sstate', models.CharField(max_length=30)),
                ('scountry', models.CharField(max_length=30)),
            ],
        ),
    ]
