# Generated by Django 3.0.2 on 2020-07-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_studentregistrationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistrationmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='sidno',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
