# Generated by Django 3.0.2 on 2020-07-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200717_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationmodel',
            name='spasswd',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='studentregistrationmodel',
            name='suname',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
