# Generated by Django 3.0.2 on 2020-07-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200719_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationmodel',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
