# Generated by Django 3.0.2 on 2020-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_studentenrolledcoursemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrolledcoursemodel',
            name='smobno',
            field=models.IntegerField(default=None),
        ),
    ]
