# Generated by Django 3.0.2 on 2020-07-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_studentenrolledcoursemodel_smobno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrolledcoursemodel',
            name='cdate',
        ),
        migrations.RemoveField(
            model_name='studentenrolledcoursemodel',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='studentenrolledcoursemodel',
            name='dur',
        ),
        migrations.RemoveField(
            model_name='studentenrolledcoursemodel',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='studentenrolledcoursemodel',
            name='fname',
        ),
    ]
